# Generated by Django 5.0.2 on 2024-05-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя услуги')),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, upload_to='media/сovers/')),
            ],
        ),
    ]
