# Generated by Django 5.0.2 on 2024-05-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, upload_to='media/сovers/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Услуги',
            },
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
