# Generated by Django 5.0.2 on 2024-05-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_services_service_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cover',
            field=models.ImageField(blank=True, upload_to='сovers/', verbose_name='Обложка'),
        ),
    ]
