# Generated by Django 5.0.2 on 2024-06-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_request_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='dealer',
            field=models.CharField(default='', max_length=255, verbose_name='Ссылка на дилера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='detail',
            field=models.TextField(default='', verbose_name='Детальное описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='cover',
            field=models.ImageField(upload_to='сovers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
