# Generated by Django 5.0.2 on 2024-06-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_service_dealer_service_detail_alter_service_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0, max_length=7, verbose_name='Стоимость услуги'),
            preserve_default=False,
        ),
    ]
